controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /api

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser

register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST